server:
  port: 9191
spring:
  thymeleaf:
    encoding: UTF-8
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngrcompany21@gmail.com
    password: mbkfheoqtvpvcgfn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
